; Licensed to the Apache Software Foundation (ASF) under one or more
; contributor license agreements.  See the NOTICE file distributed with
; this work for additional information regarding copyright ownership.
; The ASF licenses this file to You under the Apache License, Version 2.0
; (the "License"); you may not use this file except in compliance with
; the License.  You may obtain a copy of the License at
;
;     http://www.apache.org/licenses/LICENSE-2.0
;
; Unless required by applicable law or agreed to in writing, software
; distributed under the License is distributed on an "AS IS" BASIS,
; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
; See the License for the specific language governing permissions and
; limitations under the License.

[PHP]
short_open_tag = Off
output_buffering = Off
expose_php = Off
max_execution_time = 0
memory_limit = -1
error_reporting = E_ALL
display_errors = Off
log_errors = On
log_errors_max_len = 0
html_errors = Off
variables_order = "EGPCS"
request_order = "GP"
post_max_size = 0
enable_dl = Off
zend.assertions = -1

[opcache]
opcache.enable=1
opcache.enable_cli=1
opcache.max_accelerated_files=16229
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.validate_timestamps=0
opcache.save_comments=0
opcache.file_cache=/tmp/opcache
opcache.file_cache_only=0
opcache.file_cache_consistency_checks=0
opcache.optimization_level=0x7FFEBFFF
opcache.jit=tracing
opcache.jit_buffer_size=128M
opcache.jit_hot_func=1
opcache.jit_hot_loop=1
opcache.jit_hot_return=1
opcache.jit_hot_side_exit=1
opcache.preload_user=nobody